
version: 2

models:
    - name: demo_example
      description: "demo model"
      columns:
          - name: customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: first_name
            description: "The first name of the customer"
          - name: last_name
            description: "The last name of the customer" 
          - name: number_of_orders
            description: "The number of orders the customer has placed at Jaffle Shop" 

