version: 2

models:
  - name: fct_orders
    description: "Data on all orders with dollar amounts"
    columns:
      - name: order_id
        description: "unique identifier of the order"

      - name: customer_id
        description: "unique identifier for the customer"

      - name: order_date
        description: "Date the order was placed by the customer"

      - name: amount
        description: "Amount in USD"